# Generated by Django 6.0.3 on 2026-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('market', models.CharField(db_index=True, default='KR', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField()),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'market', 'timestamp')},
            },
        ),
    ]
