# Generated by Django 6.0.3 on 2026-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts', '0004_datafetchrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTradingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('market', models.CharField(db_index=True, default='KR', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('day_type', models.CharField(choices=[('TRADING', 'Trading Day'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday'), ('NO_DATA', 'No Data Available')], default='TRADING', max_length=20)),
                ('has_price_data', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'day_type'], name='hts_stocktr_symbol_124b65_idx'), models.Index(fields=['market', 'date'], name='hts_stocktr_market_543d48_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
