# Generated by Django 6.0.3 on 2026-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts', '0005_stocktradingcalendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datafetchrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datafetchrequest',
            name='interval',
            field=models.CharField(choices=[('1d', 'Daily'), ('1h', '1 Hour'), ('30m', '30 Minutes'), ('15m', '15 Minutes'), ('5m', '5 Minutes')], db_index=True, default='1d', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='datafetchrequest',
            unique_together={('symbol', 'start_date', 'end_date', 'interval')},
        ),
    ]
