# Generated by Django 6.0.3 on 2026-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts', '0008_add_stock_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
