# Generated by Django 6.0.3 on 2026-07-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts', '0009_increase_stock_name_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('balance', models.FloatField()),
                ('portfolio', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='COMPLETED', max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('user', 'snapshot_date')},
            },
        ),
    ]
